name: Metrics
on:
  schedule: [{cron: "0 0 1 * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Neved4
          template: classic
          base: header, activity, community, metadata
          config_timezone: Europe/Madrid
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: user
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
