name: Metrics
on:
  workflow_dispatch:
  schedule: [{cron: "0 0 1 * *"}]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Neved4
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          template: classic
          base: header, activity, community, metadata
          config_timezone: Europe/Madrid
          repositories_skipped: ad2mo
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 100000
          plugin_reactions_limit_discussions: 100000
          plugin_reactions_limit_discussions_comments: 100000
          plugin_reactions_limit_issues: 100000
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github, ruby:red
          plugin_languages_indepth: yes
          plugin_languages_limit: 16
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 150
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
